app/auth.py
from flask import Blueprint, render_template, request, flash, url_for, redirect
from .models import User, Profile
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from flask_change_password import ChangePassword, ChangePasswordForm, SetPasswordForm

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST' and 'email' in request.form and 'password' in request.form:
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if '@' in request.form.get('email') and '.' in request.form.get('email'):
            if user:
                if check_password_hash(user.password, password):
                    flash('Logged in successfully', category='success')
                    login_user(user, remember=True)
                    return redirect(url_for('views.search', user=current_user))
                else:
                    flash('Incorrect Password', category='error')
            else:
                flash('No account for this email', category='error')
        else:
            flash('Please enter a valid email address', category='error')
    return render_template(('login.html'), user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')
        full_name = request.form.get('full_name')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(full_name) < 1:
            flash('Name cannot be blank', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(username) < 2:
            flash('Username must be greater than 1 character.', category='error')
        elif len(password) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, username=username,full_name=full_name, password=generate_password_hash(
                password, method='sha256'))
            new_profile = Profile()
            db.session.add(new_user)
            db.session.add(new_profile)
            db.session.commit()
            user = User.query.filter_by(email=email).first()
            login_user(user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.search', user=current_user))

    return render_template("signup.html", user=current_user)


@auth.route('/changepassword', methods=["GET", "POST"])
@login_required
def user_password_change():
    newPassword = request.form.get('password1')
    if request.method == 'POST':
        if request.form.get('password1') == request.form.get('password2') and len(request.form.get('password1')) >= 7:
            db.session.query(User).filter_by(id=current_user.id).update(
                {User.password: generate_password_hash(newPassword)})
            db.session.commit()
            flash('Password has been updated', category='success')
            return redirect(url_for('views.dashboard'))
        else:
            flash('Please enter a valid password. Make sure they match',
                  category='error')
            return render_template('changepassword.html', user=current_user)
    else:
        return render_template('changepassword.html', user=current_user)

app/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from .models import Profile, Recipe
from . import db
from fileinput import filename
from flask import *

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template('index.html')

@views.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    if request.method == 'POST':
        search_query = request.form.get('query')
        results = Recipe.query.filter(Recipe.title.ilike('%{}%'.format(search_query))).all()
        return render_template('search.html', user=current_user, recipes=Recipe.query.all(), query=search_query, results=results)
    else:
        return render_template('search.html', user=current_user, recipes=Recipe.query.all())

@views.route('/profile')
@login_required
def profile():
    profile = Profile.query.filter_by(id=current_user.id).first()
    return render_template('profile.html', user=current_user, profile=profile, recipes=Recipe.query.filter_by(user_id=current_user.id).all())

@views.route('/profile/update', methods=['GET','POST'])
@login_required
def update_profile():
    profile = Profile.query.filter_by(id=current_user.id).first()
    user = current_user
    full_name = request.form.get('full_name')
    username = request.form.get('username')
    email = request.form.get('email')
    bio = request.form.get('bio')

    if request.method == 'POST':
        user.full_name = full_name
        user.username = username
        user.email = email
        profile.bio = bio

        db.session.commit()
        return redirect(url_for('views.profile', user=user, profile=profile, recipes=Recipe.query.filter_by(user_id=current_user.id).all()))
    return render_template('profile_settings.html', user=user, profile=profile)

@views.route('/recipe/upload', methods=['GET','POST'])
def recipe_upload():
    if request.method == 'POST':
        f = request.files['recipe_image']
        f.save(f'app/static/{f.filename}')
        user_id = current_user.id
        title = request.form.get('title')
        prep_time = request.form.get('prep_time')
        servings = request.form.get('servings')
        ingredients = request.form.get('ingredients')
        directions = request.form.get('directions')
        photo_path = f.filename
        print(photo_path)
        new_recipe = Recipe(user_id=user_id, username=current_user.username, title=title, time=prep_time, servings=servings, ingredients=ingredients, directions=directions, photo_path=photo_path)
        db.session.add(new_recipe)
        db.session.commit()
        profile = Profile.query.filter_by(id=current_user.id).first()
        return render_template("profile.html", user=current_user, profile=profile, recipes=Recipe.query.filter_by(user_id=current_user.id).all())
    return render_template('recipe_template.html')

@views.route('/recipe/view<int:recipe_id>', methods=['GET'])
def recipe_view(recipe_id):
    return render_template('recipes.html', user=current_user, recipe=Recipe.query.filter_by(id=recipe_id).first())

@views.route('/recipe/buy', methods=['GET'])
def recipe_buy():
    return render_template('others_recipes.html')

app/templates/index.html
{% extends "base.html" %} {% block title %}Mimi's Cookbook | Home{% endblock %}
{% block content %}
<script src="{{url_for('static', filename='/js/index.js')}}"></script>
<div class="homepage-content">
  <div class="homepage-text-left"></div>
  <div class="homepage-text-right">
    <p class="homepage-welcome">Welcome to Mimi's Cookbook!</p>
    <p class="homepage-subwelcome">Sign in  to view our assortment of recipes.</p>
    <div class="sign-in-btn">
      <a href="{{ url_for('auth.login') }}">Sign In</a>
    </div>
  </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block title %}Mimi's Cookbook | Log In{% endblock %}
{% block content %}
<div class="navbar">
    <a href="/" class="back-home-link">
        <i class="fas fa-arrow-left"></i> Back to Home
    </a>
</div>
<div class="login">
    <h1>Login</h1>
    <div class="links">
        <a href="{{ url_for('auth.login') }}" class="active">Login</a>
        <a href="{{ url_for('auth.register') }}">Register</a>
    </div>
    <form action="{{ url_for('auth.login') }}" method="post">
        <label for="email">
            <i class="fas fa-envelope"></i>
        </label>
        <input type="text" name="email" placeholder="Email" id="email" required>
        <label for="password">
            <i class="fas fa-lock"></i>
        </label>
        <input type="password" name="password" placeholder="Password" id="password" required>
        <div class="msg">{{ msg }}</div>
        <input type="submit" value="Login">
    </form>
</div>
{% endblock %}

app/templates/others_profile.html
{% extends "base.html" %} {% block title %}Mimi's Cookbook | Profile{% endblock
%} {% block content %}
<script src="{{url_for('static', filename='/js/index.js')}}"></script>
<div class="navbar">
  <a href="/search" class="logo-text-link">
    <div class="logo-text">Mimi's Cookbook</div>
  </a>
  <form class="searchbar">
    <input type="text" name="search" placeholder="Search.." />
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>
  <div>
    <button onclick="show_hide()" class="nav-bars">
      <i class="fas fa-bars"></i>
    </button>
    <ul id="nav-links" class="nav-links">
      <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      <li><a href="{{ url_for('views.profile') }}">Profile</a></li>
    </ul>
  </div>
</div>
<div class="profile-container">
  <div class="profile-header">
    <div class="profile-img">
      <img src="{{ user.avatar(280) }}" width="200" alt="" />
    </div>
    <div class="profile-name-info">
      <h3 class="user-name">{{user.full_name}}</h3>
      <div class="user-username">
        <p>@{{user.username}}</p>
      </div>
    </div>
  </div>
  <div class="profile-body">
    <div class="left-side">
      <div class="profile-side">
        <p class="user-subscribers">
          <i class="fas fa-user-alt"></i>{{profile.subscribers}} subscribers
        </p>
        <p class="user-email"><i class="fas fa-envelope"></i>{{user.email}}</p>
        <div class="user-bio">
          <h3>Bio</h3>
          <p>{{profile.bio}}</p>
        </div>
        <div class="user-rating">
          <h3 class="rating">{{profile.rating}}</h3>
          <div class="rate">
            <div class="stars">
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
            </div>
          </div>
          <div class="no-reviews">{{profile.num_reviews}} reviews</div>
        </div>
      </div>
    </div>
    <div class="right-side">
      <div class="profile-recipes">
        <ul>
          {% for recipe in recipes %}
          <a
            ><li>
              <img
                src="{{url_for('static', filename=recipe.photo_path)}}"
                alt=""
              />
              <h4>{{recipe.title}}</h4>
              <p>@{{user.username}}</p>
              <div class="recipe-stars">
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                (0 reviews)
              </div>
            </li></a
          >
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/others_recipes.html
{% extends "base.html" %} {% block title %}Mimi's Cookbook | Recipes{% endblock
%} {% block content %}
<script src="{{url_for('static', filename='/js/index.js')}}"></script>
<div class="navbar">
  <a href="/search" class="logo-text-link">
    <div class="logo-text">Mimi's Cookbook</div>
  </a>
  <form class="searchbar">
    <input type="text" name="search" placeholder="Search.." />
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>
  <div>
    <button onclick="show_hide()" class="nav-bars">
      <i class="fas fa-bars"></i>
    </button>
    <ul id="nav-links" class="nav-links">
      <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      <li><a href="{{ url_for('views.profile') }}">Profile</a></li>
    </ul>
  </div>
</div>
<div class="view-recipe-flex-box">
  <div class="view-other-recipe">
    <div class="buy-display-recipe-name">
      <h3>Strawberry Pretzel Salad</h3>
      <div class="buy-recipe-user-info">
        <span class="buy-display-recipe-user">@morganhepler</span>
        <span class="recipe-stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <span class="buy-recipe-reviews">(0 reviews)</span>
        </span>
      </div>
    </div>
    <div class="recipe-part">
      <div class="ingredient-list-hide">
        <h4>Ingredients</h4>
        <p>6 oz strawberry Jell-O</p>
        <p>2 cups boiling water</p>
        <p>2 1/2 cups salted pretzels, (measured before crushing)</p>
        <p>1/4 cup granulated sugar</p>
        <p>8 Tbsp unsalted butter</p>
        <p>8 oz package cream cheese, softened</p>
        <p>1/2 cup granulated sugar</p>
        <p>8 oz cool whip, thawed in the fridge</p>
        <p>1 lb fresh strawberries, hulled and sliced</p>
      </div>
      <div class="right-half">
        <div class="recipe-img">
          <img src="../static/strawberry-pretzel-salad.webp" />
        </div>
        <div class="time-and-servings">
          <div class="buy-recipe-info">
            <h5>Time to Prepare</h5>
            <p>30min</p>
          </div>
          <div class="buy-recipe-info">
            <h5>Servings</h5>
            <p>8</p>
          </div>
        </div>
      </div>
    </div>
    <div class="recipe-part">
      <div class="direction-list-hide">
        <h4>Directions</h4>
        <ol>
          <li>
            <p>
              Pre-heat oven to 350°F. Combine strawberry Jell-O with 2 cups
              boiling water and stir until completely dissolved. Set aside to
              cool to room temperature.
            </p>
          </li>
          <li>
            <p>
              Crush 2 1/2 cups pretzels in a sturdy ziploc bag, using a rolling
              pin.
            </p>
          </li>
          <li>
            <p>
              In a medium sauce pan, melt 8 Tbsp butter then add 1/4 cup sugar
              and stir. Mix in crushed pretzels. Transfer to a 13x9 glass
              casserole dish, pressing the pretzel mix evenly over the bottom of
              the dish and bake for 10 min at 350°F, then cool to room temp.
            </p>
          </li>
          <li>
            <p>
              When pretzels have cooled, use an electric hand mixer to beat 8 oz
              cream cheese and 1/2 cup sugar on med/high speed until fluffy and
              white. Fold in 8 oz Cool Whip until no streaks of cream cheese
              remain. Spread mixture over cooled pretzels, spreading to the
              edges of the dish to create a tight seal. Refrigerate 30 min.
            </p>
          </li>
          <li>
            <p>
              Hull and slice 1 lb strawberries then stir into your room
              temperature jello. Pour and spread strawberry jello mixture evenly
              over your cooled cream cheese layer and refrigerate until jello is
              set (2-4 hours).
            </p>
          </li>
        </ol>
      </div>
    </div>
  </div>
  <div class="buy-recipe">
    <div class="buy-recipe-price">
      <h3>$1.00</h3>
    </div>
    <div class="buy-recipe-name">Strawberry Pretzel Salad</div>
    <div class="buy-recipe-rating">
      <span class="buy-recipe-stars">
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <span class="buy-recipe-user">by @morganhepler</span>
      </span>
    </div>
    <button class="add-to-cart-btn">
      <i class="fas fa-plus"></i>Add to Cart
    </button>
  </div>
</div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}
{% block title %}Mimi's Cookbook | Profile{% endblock %}
{% block content %}
<script src="{{url_for('static', filename='/js/index.js')}}"></script>
<div class="navbar">
    <a href="/search" class="logo-text-link">
        <div class="logo-text">
            Mimi's Cookbook
        </div>
    </a>
    <form class="searchbar">
        <input type="text" name="search" placeholder="Search..">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
    <div>
        <button onclick="show_hide()" class="nav-bars"><i class="fas fa-bars"></i></button>
        <ul id='nav-links' class="nav-links">
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            <li><a href="{{ url_for('views.profile') }}">Profile</a></li>
        </ul>
    </div>
</div>
<div class="profile-container">
    <div class="profile-header">
        <div class="profile-img">
            <img src="{{ user.avatar(280) }}" width="200" alt="">
        </div>
        <div class="profile-name-info">
            <h3 class="user-name">{{user.full_name}}</h3>
            <div class="user-username">
                <p>@{{user.username}}</p>
            </div>
        </div>
        <div class="uploadbtn-container">
            <a href="{{ url_for('views.recipe_upload') }}">
                <button class="uploadbtn"><i class="fas fa-plus"></i><span class="hide-upload-btn-content">Upload Recipe</span></button>
            </a>
        </div>
    </div>
    <a href="{{ url_for('views.update_profile') }}">
        <button class="settingsbtn2"><i class="fa fa-gear"></i></button>
    </a>
    <div class="profile-body">
        <div class="left-side">
            <div class="profile-side">
                <p class="user-subscribers"><i class="fas fa-user-alt"></i>{{profile.subscribers}} subscribers</p>
                <p class="user-email"><i class="fas fa-envelope"></i>{{user.email}}</p>
                <div class="user-bio">
                    <h3>Bio</h3>
                    <p>{{profile.bio}}</p>
                </div>
                <div class="user-rating">
                    <h3 class="rating">{{profile.rating}}</h3>
                    <div class="rate">
                        <div class="stars">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        </div>
                    </div>
                    <div class="no-reviews">
                        {{profile.num_reviews}} reviews
                    </div>
                </div>
                <a href="{{ url_for('views.update_profile') }}">
                    <button class="settingsbtn1"><i class="fa fa-gear"></i>Profile Settings</span></button>
                </a>
            </div>
        </div>
        <div class="right-side">
            <div class="profile-tabs">
                <ul>
                    <li><button class="tabs-btn active">Uploaded Recipes</button></li>
                    <li><button class="tabs-btn">Purchased Recipes</button></li>
                </ul>
            </div>
            <div class="profile-recipes">
                <ul>
                    {% for recipe in recipes %}
                    <a href="{{ url_for('views.recipe_view', recipe_id=recipe.id) }}"><li>
                        <img src="{{url_for('static', filename=recipe.photo_path)}}" alt="">
                        <h4>{{recipe.title}}</h4>
                        <p>@{{user.username}}</p>
                        <div class="recipe-stars">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            (0 reviews)
                        </div>
                    </li></a>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile_settings.html
{% extends "base.html" %}
{% block title %}Mimi's Cookbook | Settings{% endblock %}
{% block content %}
<script src="{{url_for('static', filename='/javascript/javascript.js')}}"></script>
<div class="navbar">
    <a href="/search" class="logo-text-link">
        <div class="logo-text">
            Mimi's Cookbook
        </div>
    </a>
    <form class="searchbar">
        <input type="text" name="search" placeholder="Search..">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
    <div>
        <button onclick="show_hide()" class="nav-bars"><i class="fas fa-bars"></i></button>
        <ul id='nav-links' class="nav-links">
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            <li><a href="{{ url_for('views.profile') }}">Profile</a></li>
        </ul>
    </div>
</div>

<div class="profile-settings-box">
    <div class="setting-heading-color">
        <h3>Profile Picture</h3>
    </div>
    <div>
        <p>Current profile picture</p>
        <div class="profile-img-settings">
            <img src="{{ user.avatar(280) }}" width="200" alt="">
        </div>
    </div>
    <hr />
    <h3>Change your profile picture</h3>
    <p><span class="bolder-font">Changing your profile picture on Gravatar:</span><br />
        <span class="smaller-font">Click the link to vist <a href="https://en.gravatar.com/" target="_blank">Gravatar.com</a><br />
        Create an account using the same email used for Mimi's Cookbook<br />
        Upload the image you want to use as your profile picture<br />
        The picture will automatically link to your Mimi's Cookbook account!</span></p>
</div>

<form action="{{ url_for('views.update_profile') }}" method="POST">
    <div class="profile-settings-box">
        <div class="setting-heading-color">
            <h3>Name</h3>
        </div>
        <label for="full_name">
            <i class="fas fa-signature"></i>
        </label>
        <input type="text" name="full_name" placeholder="{{ user.full_name }}" id="full-name" value="{{ user.full_name }}">
    </div>

    <div class="profile-settings-box">
        <div class="setting-heading-color">
            <h3>Username</h3>
        </div>
        <label for="username">
            <i class="fas fa-user"></i>
        </label>
        <input type="text" name="username" placeholder="{{ user.username }}" id="username" value="{{ user.username }}">
    </div>

    <div class="profile-settings-box">
        <div class="setting-heading-color">
            <h3>Email</h3>
        </div>
        <label for="email">
            <i class="fas fa-envelope"></i>
        </label>
        <input type="email" name="email" placeholder="{{ user.email }}" id="email" value="{{ user.email }}">
    </div>

    <div class="profile-settings-box">
        <div class="setting-heading-color">
            <h3>Bio</h3>
        </div>
        <label for="bio">
            <i class="fas fa-scroll"></i>
        </label>
        <input type="text" name="bio" placeholder="{{ profile.bio }}" id="bio" value="{{ profile.bio }}">
    </div>
    <input class="change-btn" type="submit" value="Update Profile">
</form>
{% endblock %}

app/templates/recipe_template.html
{% extends "base.html" %}
{% block title %}Mimi's Cookbook | Upload{% endblock %}
{% block content %}
<script src="{{url_for('static', filename='/js/index.js')}}"></script>
<div class="navbar">
    <a href="/search" class="logo-text-link">
        <div class="logo-text">
            Mimi's Cookbook
        </div>
    </a>
    <form class="searchbar">
        <input type="text" name="search" placeholder="Search..">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
    <div>
        <button onclick="show_hide()" class="nav-bars"><i class="fas fa-bars"></i></button>
        <ul id='nav-links' class="nav-links">
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
            <li><a href="{{ url_for('views.profile') }}">Profile</a></li>
        </ul>
    </div>
</div>
<div class="upload-form-container">
    <div class="upload-form">
        <form action="{{ url_for('views.recipe_upload') }}" method="POST" enctype="multipart/form-data">
            <div class="recipe-name">
                <label for="title">Recipe Name:&nbsp;</label>
                <input type="text" id="title" name="title">
            </div>
            <div class="time-and-servings">
                <div>
                    <label for="prep_time">Time to Prepare:</label>
                    <input type="text" id="prep_time" name="prep_time"/>
                </div>
                <div>
                    <label for="servings">Servings:</label>
                    <input type="text" id="servings" name="servings"/>
                </div>
            </div>
            <div class="ingredients">
                <label for="ingredients">Ingredients:</label>
                <textarea id="ingredients" name="ingredients" onInput="bulletedInput(event)" rows="8"></textarea>
            </div>
            <div class="directions">
                <label for="directions">Directions:</label>
                <textarea id="directions" name="directions" onInput="bulletedInput(event)" rows="10"></textarea>
            </div>
            <div class="recipe-image">
                <button type="button" class="upload-image-btn">
                <i class="fa fa-upload"></i> Upload Image
                <input type="file" accept="Image/*" id="recipe_image" name="recipe_image"/>
                <output id="file_output" name="file_output"></output>
            </div>
            <div class="submit-upload">
                <input type="submit" value="Submit My Recipe!">
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/recipes.html
{% extends "base.html" %} {% block title %}Mimi's Cookbook | Recipes{% endblock
%} {% block content %}
<script src="{{url_for('static', filename='/js/index.js')}}"></script>
<div class="navbar">
  <a href="/search" class="logo-text-link">
    <div class="logo-text">Mimi's Cookbook</div>
  </a>
  <form class="searchbar">
    <input type="text" name="search" placeholder="Search.." />
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>
  <div>
    <button onclick="show_hide()" class="nav-bars">
      <i class="fas fa-bars"></i>
    </button>
    <ul id="nav-links" class="nav-links">
      <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      <li><a href="{{ url_for('views.profile') }}">Profile</a></li>
    </ul>
  </div>
</div>
<div class="view-recipe">
  <div class="display-recipe-name">
    <h3>{{recipe.title}}</h3>
    <div class="recipe-user-info">
      <span class="recipe-user">@{{recipe.username}}</span>
      <span class="recipe-stars">
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <span class="recipe-reviews">(0 reviews)</span>
      </span>
    </div>
  </div>
  <div class="recipe-part">
    <div class="ingredient-list">
      <!-- <h4>Ingredients</h4>
            <p>6 oz strawberry Jell-O</p>
            <p>2 cups boiling water</p>
            <p>2 1/2 cups salted pretzels, (measured before crushing)</p>
            <p>1/4 cup granulated sugar</p>
            <p>8 Tbsp unsalted butter</p>
            <p>8 oz package cream cheese, softened</p>
            <p>1/2 cup granulated sugar</p>
            <p>8 oz cool whip, thawed in the fridge</p>
            <p>1 lb fresh strawberries, hulled and sliced</p> -->
      <h4>Ingredients</h4>
      <p id="recipe-ingredients"><span>{{recipe.ingredients}}</span></p>
    </div>
    <div class="right-half">
      <div class="recipe-img">
        <img src="{{url_for('static', filename=recipe.photo_path)}}" />
      </div>
      <div class="time-and-servings">
        <div class="recipe-info">
          <h5>Time to Prepare</h5>
          <p>{{recipe.time}}</p>
        </div>
        <div class="recipe-info">
          <h5>Servings</h5>
          <p>{{recipe.servings}}</p>
        </div>
      </div>
      <div class="space"></div>
    </div>
  </div>
  <div class="recipe-part">
    <div class="direction-list">
      <h4>Directions</h4>
      <p id="recipe-directions">
        <span>{{recipe.directions}}</span>
      </p>
    </div>
  </div>
</div>
{% endblock %}

app/templates/search.html
{% extends "base.html" %} {% block title %}Mimi's Cookbook | Home{% endblock %}
{% block content %}
<script src="{{url_for('static', filename='/js/index.js')}}"></script>
<div class="navbar">
  <a href="/search" class="logo-text-link">
    <div class="logo-text">Mimi's Cookbook</div>
  </a>
  <form class="searchbar" id="search-form" method="POST">
    <input type="text" name="query" id="query" placeholder="Search.." />
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>
  <div>
    <button onclick="show_hide()" class="nav-bars">
      <i class="fas fa-bars"></i>
    </button>
    <ul id="nav-links" class="nav-links">
      <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
      <li><a href="{{ url_for('views.profile') }}">Profile</a></li>
    </ul>
  </div>
</div>
<div class="welcome-msg">
  {{user.full_name}},
  <p>Welcome to Mimi's Cookbook!</p>
</div>

<div class="homepage-recipes">
  <ul>
    {% if results %} {% for result in results %}
    <a href="{{ url_for('views.recipe_view', recipe_id=result.id) }}">
      <li>
        <img src="{{url_for('static', filename=result.photo_path)}}" alt="" />
        <h4>{{result.title}}</h4>
        <p>@{{result.username}}</p>
        <div class="recipe-stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          (0 reviews)
        </div>
      </li></a
    >
    {% endfor %} {% else %} {% for recipe in recipes %}
    <a href="{{ url_for('views.recipe_view', recipe_id=recipe.id) }}">
      <li>
        <img src="{{url_for('static', filename=recipe.photo_path)}}" alt="" />
        <h4>{{recipe.title}}</h4>
        <p>@{{recipe.username}}</p>
        <div class="recipe-stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          (0 reviews)
        </div>
      </li></a
    >
    {% endfor %} {% endif %}
  </ul>
</div>

{% endblock %}